### ISSUE TITLE
Performance impact due to msgpack

### ISSUE THREAD

**Issue by carstenschwede** [JoshuaWise/jellysocket#3]
While msgpack produces smaller serializations in comparison to JSON, the process of encoding/decoding seems to be a lot slower:

https://jsperf.com/msgpack-vs-json-perf/12

Sample run in Chrome:

    MsgPack: 7,911 ops/second
    JSON: 212,227 ops/second

**Edit/Update**
When using the correct msgpack-package at https://jsperf.com/msgpack-vs-json-perf/13 the results are

    MsgPack: 38,092 ops/second
    JSON: 208.359 ops/second

A benchmark test might be nice to get a better idea about the tradeoffs involved (e.g. msgpack might be better for larger serializations when the duration of transfer exceeds the duration of encoding/decoding).

**Comment by JoshuaWise** [comment]
The msgpack library used in that benchmark isn't the same one used by JellySocket. The one we use is known to be much faster and encoding and decoding.

After redoing this test with the correct package, we get better results:
http://jsperf.com/msgpack-vs-json-perf/13

Instead of only being 3% as fast, we are now 80% as fast at numbers, and 20% as fast at strings.

However, where it REALLY matters is in Node, not in the browser. Although Chrome and Node both use the v8 engine, they can have very different performance characteristics due to certain optimizations that Node takes advantage of.

Implementing the same test as a Node.js script, we get even better results:
```
#!/usr/bin/env node
var msgpack = require('msgpack-lite');
var stringData = {"glossary":{"title":"example glossary","GlossDiv":{"title":"S","GlossList":{"GlossEntry":{"ID":"SGML","SortAs":"SGML","GlossTerm":"Standard Generalized Markup Language","Acronym":"SGML","Abbrev":"ISO 8879:1986","GlossDef":{"para":"A meta-markup language, used to create markup languages such as DocBook.","GlossSeeAlso":["GML","XML"]},"GlossSee":"markup"}}}}};
var numberData = [
	[1, 2, 3, 4, -1, true, null],
	[3, 6, 5, 4,  1, false, 7],
	[3, 2, 8, 1,  0, true, 0],
	[10, 11, 12, 13,  14, false, true],
	[15, 16, 17, 18, 19, true, null],
	[20, 21, 22, 23,  24, false, 7],
	[25, 26, 27, 28,  29, true, 0],
	100, 200, 300,
	[
		[1, 0, 0, 0, 0],
		[0, 1, 0, 0, 0],
		[0, 0, 1, 0, 0],
		[0, 0, 0, 1, 0],
		[0, 0, 0, 0, 1]
	]
];

function test(fn) {
	var times = [];
	var endTime = Date.now() + 4000;
	do {
		var t1 = process.hrtime();
		fn();
		var td = process.hrtime(t1);
		times.push(td[0] * 1e9 + td[1]);
	} while (Date.now() < endTime)
	var totalTime = times.reduce(function (a, b) {return a + b;}, 0);
	var averageTime = totalTime / times.length;
	return Math.round(averageTime) + ' nanoseconds (' + times.length + ' tests)';
}

function JSON_strings() {
	return JSON.parse(JSON.stringify(stringData));
}
function JSON_numbers() {
	return JSON.parse(JSON.stringify(numberData));
}
function msgpack_strings() {
	return msgpack.decode(msgpack.encode(stringData));
}
function msgpack_numbers() {
	return msgpack.decode(msgpack.encode(numberData));
}

console.log('JSON (strings): ' + test(JSON_strings));
console.log('JSON (numbers): ' + test(JSON_numbers));
console.log('msgpack (strings): ' + test(msgpack_strings));
console.log('msgpack (numbers): ' + test(msgpack_numbers));
```

On my machine, msgpack performs equally to JSON when dealing with numbers, and 30% as fast when dealing with strings.


You might think that 30% is a big performance loss, but encoding an decoding is actually a relatively small aspect of the total performance in a websocket transport layer. You likely wouldn't notice it very much, if at all. However, I do plan on setting up a real-world benchmark for JellySocket soon to address issues like this.

**Comment by JoshuaWise** [comment]
Yes, I think it's a good idea to keep it open until I create a solid benchmark.

Thanks for being interested in JellySocket!

**Comment by JoshuaWise** [comment]
Closing this issue, since JellySocket 1.0 is very very different from previous versions. See #4 for details and/or complaints.
